name: discord_dart
version: 0.7.2
description: A Discord library for Dart
author: Hackzzila <admin@hackzzila.com>
homepage: https://github.com/Hackzzila/Discord-Dart
dependencies:
  http: ">=0.11.3+9 <0.12.0"
  events: ">=0.1.2+1 <0.2.0"
