name: discord_dart
version: 0.4.0
description: A Discord library for Dart
author: Hackzzila <admin@hackzzila.com>
homepage: https://github.com/Hackzzila/Discord-Dart
dependencies:
  http: ">=0.11.3+9 <0.12.0"
